### ISSUE TITLE
Error: `textDocument/references` not supported

### ISSUE THREAD

**Issue by chrisgrieser** [roobert/action-hints.nvim#2]
After setting up the default config as well as copypasting the lualine snippet, I get this, even though I am using an LSP server that supports both references and definitions
![CleanShot 2023-02-13 at 14 20 10](https://user-images.githubusercontent.com/73286100/218469420-7aca747b-c127-4f93-babf-38006fe9b87e.png)

**Comment by roobert** [comment]
Hi Chris, which LSP server?

**Comment by chrisgrieser** [comment]
Lua lsp (sumneko)

**Comment by roobert** [comment]
Please could you confirm whether there is an issue with another language such as python/pyright?

I have tested editing a lua file using sumneko LSP and can confirm that the plugin doesn't appear to show the information for lua, however, I don't see any errors.

I'd like to narrow down whether the problem is something to do with a specific LSP server, or something else..

Thanks!

**Comment by gagbo** [comment]
I just hit the same issue with rust-analyzer

```
Error executing vim.schedule lua callback: ...e-action-hints.nvim/lua/statusline-action-hints/init.lua:25: RPC[Error] code_na
me = InvalidParams, message = "Failed to deserialize textDocument/references: invalid value: string \"/path/to/src/lexer.rs\", expected relative URL without a base; {\"context\":{\"includeDeclaration\":true},\"position\":{\
"character\":14,\"line\":39},\"textDocument\":{\"uri\":\"/path/to/src/lexer.rs\"}}"
stack traceback:
        [C]: in function 'error'
        ...e-action-hints.nvim/lua/statusline-action-hints/init.lua:25: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

It triggers on any cursor movement at least, maybe more often (at that point the error raises too often for me to track)

**Comment by roobert** [comment]
> I just hit the same issue with rust-analyzer
> 
> ```
> Error executing vim.schedule lua callback: ...e-action-hints.nvim/lua/statusline-action-hints/init.lua:25: RPC[Error] code_na
> me = InvalidParams, message = "Failed to deserialize textDocument/references: invalid value: string \"/path/to/src/lexer.rs\", expected relative URL without a base; {\"context\":{\"includeDeclaration\":true},\"position\":{\
> "character\":14,\"line\":39},\"textDocument\":{\"uri\":\"/path/to/src/lexer.rs\"}}"
> stack traceback:
>         [C]: in function 'error'
>         ...e-action-hints.nvim/lua/statusline-action-hints/init.lua:25: in function 'handler'
>         /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
>         vim/_editor.lua: in function <vim/_editor.lua:0>
> ```
> 
> It triggers on any cursor movement at least, maybe more often (at that point the error raises too often for me to track)

Hi, this looks like a different problem, would you mind opening a separate issue so we can solve these issues separately? Thanks!

**Comment by chrisgrieser** [comment]
Just tested with tsserver and pyright, I get the very same message there as well

**Comment by roobert** [comment]
Hey, I have done a fairly major rewrite and the plugin now also supports virtual text. I think I have also fixed this bug!

**Comment by chrisgrieser** [comment]
Hi, thanks for the fix.

While the error does not occur anymore, the plugin apparently still does not fully work.  Neither the statusline component, nor the virtual text appear. I use the default config I copypasted from the readme, and tried with tsserver, bash-ls, pyright, and lua_ls.

Running `:lua= require("action-hints").statusline()` also results in no output.

**Comment by roobert** [comment]
Please update the module again then try to run:

```lua
:lua print(vim.inspect(require("action-hints").supports_method("definitionProvider")))
```

and 

```lua
:lua print(vim.inspect(require("action-hints").supports_method("referencesProvider")))
```

Both of these should return `true` if neovim is configured correctly with LSP client(s)/server(s) that supports definitions and references.

**Comment by chrisgrieser** [comment]
both return true, yet there is nothing in the status line and no virtual text at all. I am on nvim 0.9.1, in case this plugin relies on some feature from nightly?

**Comment by roobert** [comment]
I'm also using 0.9.1 installed via brew. I'm not sure what else could be the problem but I am interested in trying to understand why this isn't working for you.

I'd suggest either you make a local copy of the plugin, then add print statements into the code to see at which point it's failing, or sharing your neovim config to see if I can recreate the problem locally.

I'm using [`lazyvim/starter`](https://github.com/LazyVim/starter) as a base for my config so I'm not sure if there is some magic happening with the lsp config in it.

**Comment by chrisgrieser** [comment]
I tried to use the most minimal config possible, with nothing but LSP setup and action-hints. Both your commands still return `true`, but I do not get any virtual text.

```lua
local root = vim.fn.fnamemodify("./debug/install-root", ":p")
for _, name in ipairs { "config", "data", "state", "cache" } do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local plugins = {
	{
		"williamboman/mason-lspconfig.nvim",
		dependencies = { "williamboman/mason.nvim", opts = true },
		opts = { ensure_installed = { "lua_ls" } },
	},
	{
		"neovim/nvim-lspconfig",
		init = function() require("lspconfig")["lua_ls"].setup {} end,
	},
	{
		"roobert/action-hints.nvim",
		config = function()
			require("action-hints").setup {
				template = {
					{ " ?", "ActionHintsDefinition" },
					{ " ?%s", "ActionHintsReferences" },
				},
				use_virtual_text = true,
				definition_color = "#add8e6",
				reference_color = "#ff6666",
			}
		end,
	},
}

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system {
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable",
		lazypath,
	}
end
vim.opt.runtimepath:prepend(lazypath)
require("lazy").setup(plugins)
```

**Comment by roobert** [comment]
Think I found the problem - please try updating but note the difference in config..!

**Comment by chrisgrieser** [comment]
nice, it's working now! just so you know, it appears that this plugin won't work when used together with [trld.nvim](https://github.com/Mofiqul/trld.nvim). But after disabling trld, it did indeed work

**Comment by roobert** [comment]
I'm guessing this has to do with trld setting up `autocmd` on `CursorMoved`:
```
vim.cmd [[ autocmd! CursorMoved,CursorMovedI * lua TRLD.Hide() ]]
```
If you want both, you could setup a custom CursorMoved command that calls both TRLD and action-hints update
